### ISSUE TITLE
Integration von Talk und Collabora in docker-compose.yaml

### ISSUE THREAD

**Issue by DeCeReH** [cbirkenbeul/docker-homelab#33]
Hallo,
ich würde gerne die Funktionen Talk und Collabora mit in die config einbinden und habe mir die Anleitung von https://help.nextcloud.com/t/howto-ubuntu-docker-nextcloud-talk-collabora/76430 zur Hilfe genommen. Bei dieser Anleitung ist in der Docker Config geschrieben, das man für Collabora die Adresse COLLABORA_FQDN=office.domain.name nehmen soll. Muss da zusätzlich in der docker-compose.yaml unter labels einen Eintrag für office.domain.name hinzugefügt werden und in der traefik config ergänzt werden, oder was muss ich da genau machen, dass ich zum Beispiel OnlyOffice über office.domain.name erreichen kann?

**Comment by mr-bolle** [comment]
Seit Nextcloud 18 (Hub) ist keine separate Konfiguration für onlyoffice notwendig. Wenn du keinen separaten Nextcloud Talk Server benötigst (zB [coturn](https://nextcloud-talk.readthedocs.io/en/latest/TURN/)) brauchst du ebenfalls nichts.

**Comment by DeCeReH** [comment]
Vielen Dank für die Antwort. Onlyoffice läuft jetzt. Einen Nextcloud Talk Server benötige ich schon. Gäbe es da eine Lösung? Ich habe einige Anleitungen durch probiert, aber ohne Erfolg.

**Comment by mr-bolle** [comment]
Schau dir den oben genannten Link an, ich nutze aber den Talk Server welchen die Nextcloud mitbringt.

**Comment by stereu** [comment]
Hat nichts mit dem Projekt hier zu tun. Falls deine Frage gelöst wurde bitte schließen @DeCeReH

**Comment by DeCeReH** [comment]
@stereu 

Ich denke schon, das es mit dem Projekt zu tun hat.

Denn es gibt auch Docker Container für Coturn.

**Comment by DeCeReH** [comment]
> Schau dir den oben genannten Link an, ich nutze aber den Talk Server welchen die Nextcloud mitbringt.

Danke, ich werde es mal ausprobieren.

**Comment by cbirkenbeul** [comment]
Ich schau mir das die Tage mal an. Ich möchte es nur ungern in die bestehende Config mit integrieren, da nicht jeder dafür einen Einsatzzweck hat. Es würde dann eine dedizierte docker-compose.yaml Datei geben.
Wenn du es hin bekommen hast, füge ich sie gern dem Projekt hinzu. Einfach ein pull request erstellen.

**Comment by mighty-services** [comment]
ich bin ebenfalls an so etwas interessiert.

Eigene Versuche (mit Tutorials aus dem Netz) schlugen bis jetzt fehl.

**Comment by mighty-services** [comment]
ich habe mal waghalsig die den Config-Part aus [dieser Anleitung](https://help.nextcloud.com/t/howto-ubuntu-docker-nextcloud-talk-collabora/76430) übernommen

folgende Schritte habe ich durchgeführt:

1. Nextcloud mit `docker pull` und `docker compose up -d` auf Version 20.0.1.1 hochgezogen
2. die Docker-compose.yml Datei angepasst
   ```yml
   nextcloud-coturn:
    image: instrumentisto/coturn
    container_name: nextcloud-coturn
    restart: unless-stopped
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
    networks:
      - traefik_proxy
    command:
      - -n
      - --log-file=stdout
      - --min-port=49160
      - --max-port=49200
      - --realm=nextcloud.mydomain.com
      - --use-auth-secret
      - --static-auth-secret=mysupersecretkey
    ```
    WICHTIG! Die Werte ändern für `realm` und `static-auth-secret`
3. nach dem Abspeichern die Container neu starten mit `docker-compouse up -d`
4. den definierten Port im eigenen Router freigeben (hier 3478)
5. die Talk-App installiert - wenn nicht schon vorhanden
6. die Konfiguration für STUN und TURN angepasst in den Einstellungen (siehe angefügtes Bi
![firefox_TnBMz6GodB](https://user-images.githubusercontent.com/71066192/97415453-8d3c4400-1905-11eb-9c45-88a6acc8c860.jpg)
ld)
Nach klick auf das Symbol vor dem Mülleimer dürfte nach einiger Weile ein Hacken erscheinden. Dann ist der Server erreichbar und erfolgreich eingerichter

WICHTIG! Erst als ich identische Werte bei STUN und TURN eingetragen hatte funktionierte die Anbindung der Talk-App auf Iphone und Android

Fertig.

Ich habe nur wenig Ahnung von Docker, Nextcloud, coTURN etc. und kann euch bei Fehler und Fragen nur wenig helfen ... aber vielleicht ist diese kleine Anleitung ja für manchen schon eine Hilfe an Sich.
