### ISSUE TITLE
Treafik externes Routing

### ISSUE THREAD

**Issue by mighty-services** [cbirkenbeul/docker-homelab#51]
Hallo ich nutze nun seid Ihrer superschnellen Hilfe gestern die aktuelle Traefik-Version mit den hier zur Verfügung stehenden Konfigurationen.

Traefik 2.3 läuft bei mir auf einem Ubuntu-Server 20lts und beinhaltet schon einige Docker-Images. Da ich nun eine [Standard Notes ](https://bowlerdesign.tech/posts/how-to-completely-self-host-standard-notes/) Instanz aufbauen möchte, dies aber laut dieser Umschreibung einige Einstellungen am Host-System braucht würde ich das gerne auf einer separaten Linux-VM tun.

Meine Frage ist nun, wie kriege ich Traefik dazu eine Subdomain an einen im LAN befindlichen Server weiter zu leiten? Alle gefundenen Tutorials basieren auf YML-Konfigurationen und waren für mich (der Einsteiger in Traefik ist) nicht umsetzbar.

**Comment by mighty-services** [comment]
Sie können natürlich auch gerne eine Anleitung schreiben, wie man Standard-Notes in traefik impleentiert...aber das wäre erst mein nächster Schritt :)

**Comment by cbirkenbeul** [comment]
Ich möchte die Webseite nicht aufmachen, weil da kein valides Zertifikat hinterlegt ist.

Die Einrichtung von statischen Konfigurationen werden über die traefik.toml gemacht, alternativ kann man natürlich auch weitere Dateien als yaml dort rein laden. Die Konfiguration des ganzen steht schon länger auf meiner Liste weil ich eine ähnliche Anforderung im privaten Homelab habe.

Das Thema werde ich mir einmal anschauen, kann allerdings nicht versprechen wie schnell ich mit einer Lösung sein werde.

**Comment by mighty-services** [comment]
oh, okay, also bei mir kommt keine Zertifikatswarnung:
![grafik](https://user-images.githubusercontent.com/71066192/94653661-34748e00-02fc-11eb-9af6-fcd3a8391729.png)

Kein Problem, ich komme erstmal so zurecht, da die Anleitung des [Standard-Werkes](https://docs.standardnotes.org/self-hosting/docker/) schon mal mit meinem Laptop funktioniert, nur die Synchronisation mit dem Smartphone will noch nicht.

Wenn es einfacher ist, würde es für mich (jetzt zumindest) bei weitem ausreichen das Tutorial mit dem Traefik-Labels zu versehen. Anscheinend braucht der Client nicht nur Port 3000, sondern auch Port 80, aber das habe ich nur in irgendeinem Forum gelesen und nicht getestet.

**Comment by dvogt23** [comment]
Wie wäre es damit: https://github.com/standardnotes/syncing-server/blob/develop/docker-compose.yml aus dem official repo

**Comment by mighty-services** [comment]
Danke für die schnele Antwort.

Das docker-compose-File habe ich schon. In der offiziellen Anleitung ist der erste Schritt sich das Repo herunterzuladen und dann nur noch die persönlichen Sachen zu ändern. Ich bin parallel im Kontakt mit dme Hersteller wegen dem Verbindungsproblem zum Handy, nur wäre es gut auf lange Sicht den Container auf meinem Webhost mit allen anderen (unter Traefik) zum laufen zu kriegen. Darum brauche ich die richtige Konfig der Labels.

**Comment by mighty-services** [comment]
puh, ich habe nochmal von null angefangen und mir das ofizielle Tutorial auf einem separatem Server hochgezogen. Als das funktioniete habe ich es nochmal mit den Labels probiert und nun klappt die Verbindung (wahrscheinlich) über Traefik und per https. Hier meine docker-compose Datei:

```yml
version: '3.8'
services:
  app:
    build: .
    depends_on:
      - db
    command: start-local
    env_file: .env
    restart: unless-stopped
    environment:
      DB_HOST: db
    ports:
      - 3000:${EXPOSED_PORT}
    networks:
      - traefik_proxy
      - syncing_server
#      standardnotes_proxy:
#        aliases:
#          - syncing_server
 #     syncing_server: {}
    labels:
      - "traefik.enable=true"
      # HTTP-Settings
      - "traefik.http.routers.notes-http.entrypoints=web"
      - "traefik.http.routers.notes-http.rule=Host(`notes.xxxxxx.de`)"
      # HTTPS-Settings
      - "traefik.http.routers.notes-https.entrypoints=web-secure"
      - "traefik.http.routers.notes-https.rule=Host(`notes.xxxxxx.de`)"
      - "traefik.http.routers.notes-https.tls=true"
      - "traefik.http.routers.notes-https.tls.certresolver=default"
      - "traefik.http.routers.notes-https.middlewares=secHeaders@file"
      # HTTP to HTTPS redirection
#      - "traefik.http.routers.notes-http.middlewares=notes-https-redirect@docker"
#      - "traefik.http.middlewares.notes-https-redirect.redirectscheme.scheme=web-secure"
      # Services
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_proxy"
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    expose:
      - '3306'
    restart: unless-stopped
    volumes:
      - std_notes_db:/var/lib/mysql
    networks:
      - syncing_server
```

Da ich bei "App" noch zwei Netzwerke drin habe bin ich mir nicht sicher, ob er über "syncing_server" oder "traefik_proxy" die Verbindung aufbaut. Hilfe und hinweise zur Verbesserung der Datei sind herzlich willkommen :)

Das hier ist die aktuelle .env:

```yml
# Sample ENV setup Variables
# Copy this file and update as needed.
#
#   $ cp env.sample .env
#
# Do not include this new file in source control
#

# Rails Settings
EXPOSED_PORT=3000
RAILS_ENV=development
RAILS_LOG_TO_STDOUT=false
#SQS_QUEUE=somequeue
#AWS_REGION=us-west1
#S3_BACKUP_BUCKET_NAME=

ACTIVE_JOB_QUEUE_ADAPTER=async

# Database Settings
DB_PORT=3306
DB_HOST=127.0.0.1
DB_DATABASE=standard_notes_db
DB_USERNAME=std_notes_user
DB_PASSWORD=xxxxxx
DB_ROOT_PASSWORD=xxxxxx
DB_POOL_SIZE=30
DB_WAIT_TIMEOUT=180

# Secrets
# Use: bundle exec rake secret
# To generate required secrets below
#

SECRET_KEY_BASE=xxxxxx

# Disable user registration
#DISABLE_USER_REGISTRATION=true

# Datadog
DATADOG_ENABLED=false

# Mailer settings
SMTP_HOST=xxxxxx
SMTP_PORT=xxxxxx
SMTP_USERNAME=xxxxxx
SMTP_PASSWORD=xxxxxx
SMTP_DOMAIN=xxxxxx
```

ich bin mir nicht ganz sicher, ob man bei "RAILS_ENV=" nicht lieber "production" nehmen sollte.
